exclude illegal nickname
utopianf/maobot-logger-ec2 pull request #17
Opened 2022-03-02 16:46 UTC by tamagawaya

DBにとって不正と思われるnicknameからのpostをDBに入れないようにする。
IRCの規約より、nicknameの1文字目には数字が入らないので、
DBに入れるnicknameは、1文字目がa-zA-Zで、2文字目以降がa-zA-Z0-9_のはず。
fix #5

2022-03-03 06:08 UTC, utopianf commented
@tamagawaya これはここでやるのはロジック的に正しくないのかもしれない。ユーザー登録の時にnicknameがillegalかどうかをチェックするのが正しそう。

2022-03-03 14:25 UTC, tamagawaya commented
IRCからのPostのnicknameの判定のつもりなので、Log側のユーザー登録とは別かなと思いました。
Logのユーザー登録時にnicknameの制限かけるのは、別途必要かと思います。

2022-03-05 13:21 UTC, utopianf commented
IRCからのnicknameはlegalである保証がなさそう？

2022-03-05 14:09 UTC, tamagawaya commented
英数字以外に、"[", "]", "\", "`", "_", "^", "{", "|", "}"の記号は使用可能な仕様

2022-03-05 14:45 UTC, utopianf commented
なるほどそういうことか。承知です。ありがとうございます。

2022-03-05 14:50 UTC, utopianf requested changes

2022-03-05 14:50 UTC, utopianf commented on irclogger.py
> +        if not re.match(r"[a-zA-Z][a-zA-Z0-9_]*", _nickname):
これだと普通に「{hwnek}」をマッチしてしまう。`^[a-zA-Z][a-zA-Z0-9]*$`にする必要がある

2022-03-05 15:06 UTC, tamagawaya commented on irclogger.py
> +        if not re.match(r"[a-zA-Z][a-zA-Z0-9_]*", _nickname):
```
>>> not re.match(r"[a-zA-Z][a-zA-Z0-9_]*", "{hwnek}")
True
>>> not re.match(r"[a-zA-Z][a-zA-Z0-9_]*", "hw_nek")
False
```
なのですが、ダメでしょうか？
Trueでreturnして、そこで処理終わりです。

2022-03-05 15:16 UTC, tamagawaya commented
現状の変更部分より上流である、postを受け取ってすぐの、178行目、186行目付近のon_pubmsg、on_pubnoticeで処理させる方が自然かもしれない

2022-03-06 02:38 UTC, utopianf commented on irclogger.py
> +        if not re.match(r"[a-zA-Z][a-zA-Z0-9_]*", _nickname):
あーre.match()は先頭のみ見てるのですね。だとしたら以下の問題が生じる。
```
>>> not re.match(r"[a-zA-Z][a-zA-Z0-9_]*", "SSS}__")
False
```

2022-03-06 08:12 UTC, tamagawaya commented on irclogger.py
> +        if not re.match(r"[a-zA-Z][a-zA-Z0-9_]*", _nickname):
matchは途中まで合ってれば良いのか…
ということは、fullmatchを使えば良さげですかね。
```
>>> not re.fullmatch(r"[a-zA-Z][a-zA-Z0-9_]*", "SSS}__")
True
```
それとも、正規表現側でちゃんと縛る方が良いのだろうか。それならsearchだろうがなんだろうが良くなりますね。
```
>>> not re.search(r"^[a-zA-Z][a-zA-Z0-9_]*$", "SS{S__")
True
```

2022-03-06 13:10 UTC, utopianf commented on irclogger.py
> +        if not re.match(r"[a-zA-Z][a-zA-Z0-9_]*", _nickname):
re.search()のほうが（好み的に）良さそうに見えます

2022-03-07 14:56 UTC, tamagawaya commented on irclogger.py
> +        if not re.match(r"[a-zA-Z][a-zA-Z0-9_]*", _nickname):
re.searchにしました。
(authorの好みは大事)

2022-03-08 13:36 UTC, merged